# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
city_data = pd.read_csv('output_data/cities.csv')
city_data.drop(city_data.columns[0], axis = 1, inplace = True)
city_data.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Charters Towers,-20.1000,146.2667,25.55,64,62,3.85,AU,1615033280
1,Sistranda,63.7256,8.8340,2.00,75,75,14.92,NO,1615033280
2,Kumul,42.8000,93.4500,7.54,49,36,2.24,CN,1615033280
3,Ancud,-41.8697,-73.8203,15.00,100,90,5.66,CL,1615033280
4,Ahipara,-35.1667,173.1667,17.43,87,100,3.20,NZ,1615033280

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
hum = city_data['Humidity']
locations = city_data[["Lat", "Lng"]].astype(float)
heat_layer = gmaps.heatmap_layer(locations, weights=hum, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 2)
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
ideal_data = city_data.loc[(city_data['Max Temp'] < 28.00)&(city_data['Max Temp'] > 18.00)&
                           (city_data['Cloudiness'] < 5) & (city_data['Wind Speed'] < 5)] 
ideal_data.dropna()
ideal_data

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
17,Port Alfred,-33.5906,26.8910,23.33,79,0,4.47,ZA,1615033030
36,Junín,-34.5838,-60.9433,20.56,31,0,2.45,AR,1615032985
67,Salto,-31.3833,-57.9667,18.17,71,0,2.54,UY,1615033091
87,Young,-32.6833,-57.6333,20.56,70,0,0.45,UY,1615033291
105,Ubari,26.5921,12.7805,27.26,14,0,1.78,LY,1615033293
108,Mount Isa,-20.7333,139.5000,24.00,31,0,1.68,AU,1615033294
132,Hermanus,-34.4187,19.2345,23.89,72,0,4.47,ZA,1615033298
160,Bayjī,34.9311,43.4870,19.97,27,0,4.28,IQ,1615033302
180,Barra de Tecoanapa,16.5167,-98.7500,21.00,78,0,1.85,MX,1615033305
202,Comodoro Rivadavia,-45.8667,-67.5000,22.00,35,0,4.63,AR,1615033309
206,Wailuku,20.8911,-156.5047,21.00,73,1,1.54,US,1615033118
243,Colares,38.7992,-9.4469,19.00,48,0,3.09,PT,1615033313
288,Puerto Escondido,15.8500,-97.0667,23.28,69,0,1.51,MX,1615033319
296,Peniche,39.3558,-9.3811,19.44,61,0,4.02,PT,1615033197
297,Lázaro Cárdenas,17.9583,-102.2000,20.32,82,0,2.63,MX,1615033319
354,Los Algarrobos,8.5000,-82.4333,20.00,94,0,1.03,PA,1615033327
357,Pimentel,-6.8367,-79.9342,23.00,78,0,1.03,PE,1615033328
381,Susa,32.1942,48.2436,22.76,30,0,4.94,IR,1615033331
387,Bahía Blanca,-38.7196,-62.2724,20.86,38,0,3.65,AR,1615033332
404,Faya,18.3851,42.4509,27.00,9,0,4.12,SA,1615033334
422,Acapulco de Juárez,16.8634,-99.8901,21.66,75,0,2.00,MX,1615033209
424,Kiryat Gat,31.6100,34.7642,20.56,47,0,2.24,IL,1615033337
426,Quang Ngai,15.1167,108.8000,23.48,88,0,3.15,VN,1615033337
427,Dawei,14.0833,98.2000,26.30,62,0,2.20,MM,1615033337
456,Makakilo City,21.3469,-158.0858,21.00,82,1,2.57,US,1615033341
460,General Roca,-39.0333,-67.5833,19.00,82,0,1.54,AR,1615033341
465,Córdoba,-31.4135,-64.1811,25.00,88,0,4.12,AR,1615033342
480,Port Blair,11.6667,92.7500,27.42,74,0,3.48,IN,1615033344
523,Riyadh,24.6877,46.7219,25.00,15,0,3.60,SA,1615033356
538,Kahului,20.8947,-156.4700,21.00,73,1,1.54,US,1615033359
565,Nha Trang,12.2500,109.1833,26.00,83,0,1.03,VN,1615033363

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
hotel = []
city = []
cntry = []
lat = []
lng = []
for row in ideal_data.itertuples():
    try:
        coord = f'{row[2]},{row[3]}'
        search = 'Hotel'
        radius = 5000
        types = 'lodging'
        params = {
        "location": coord,
        "keyword": search,
        "radius": radius,
        "type": types,
        "key": g_key
        }
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        response = requests.get(base_url, params=params).json()
        hotel.append(response['results'][0]['name'])
        city.append(row[1])
        cntry.append(row[8])
        lat.append(response['results'][0]['geometry']['location']['lat'])
        lng.append(response['results'][0]['geometry']['location']['lng'])
    except:
        pass

In [6]:
hotel_dict = {
    'Hotel Name': hotel,
    'City': city,
    'Country': cntry,
    'Lat': lat,
    'Lng':lng
}

hotel_df= pd.DataFrame(hotel_dict)
hotel_df

,Hotel Name,City,Country,Lat,Lng
0,Royal St Andrews Hotel,Port Alfred,ZA,-33.603178,26.886978
1,PIEDRAMORA Hotel & Convention Center,Junín,AR,-34.606414,-60.961854
2,Cristobal Hotel Boutique,Salto,UY,-31.398284,-58.015057
3,Hotel Martinez,Young,UY,-32.704767,-57.631211
4,ibis Styles Mt Isa Verona,Mount Isa,AU,-20.726140,139.492803
5,Ocean Eleven,Hermanus,ZA,-34.423611,19.234444
6,Hotel Garapacho,Barra de Tecoanapa,MX,16.555608,-98.788328
7,Hotel Victoria,Comodoro Rivadavia,AR,-45.864754,-67.484340
8,Maui Beach Hotel,Wailuku,US,20.890327,-156.472478
9,Arribas Sintra Hotel,Colares,PT,38.817251,-9.475624
10,Selina Puerto Escondido,Puerto Escondido,MX,15.856837,-97.058035
11,Selina Peniche,Peniche,PT,39.368601,-9.325442
12,Hotel de Casablanca,Lázaro Cárdenas,MX,17.959975,-102.195130
13,Waterfall Hostel,Los Algarrobos,PA,8.526720,-82.421676
14,Garuda Hostal,Pimentel,PE,-6.835500,-79.937518
15,هتل و رستوران آپادانا,Susa,IR,32.194318,48.244552
16,Sofía Soberana Hotel Boutique,Bahía Blanca,AR,-38.714862,-62.268068
17,Hotel Costa Miramar,Acapulco de Juárez,MX,16.862704,-99.882400
18,Desert Gat,Kiryat Gat,IL,31.602743,34.764339
19,Tam Nam motel,Quang Ngai,VN,15.120604,108.784491
20,Hotel Deluxe,Dawei,MM,14.086680,98.189000
21,Residence Inn by Marriott Oahu Kapolei,Makakilo City,US,21.330915,-158.073203
22,Estepa Hotel,General Roca,AR,-39.029185,-67.576158
23,Sheraton Cordoba Hotel,Córdoba,AR,-31.413224,-64.202835
24,Hotel Reef Atlantis,Port Blair,IN,11.673653,92.739242
25,Four Seasons Hotel Riyadh At Kingdom Center,Riyadh,SA,24.711486,46.674529
26,Maui Beach Hotel,Kahului,US,20.890327,-156.472478
27,Alana Nha Trang Beach Hotel,Nha Trang,VN,12.233384,109.196717

In [7]:
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

locations = hotel_df[["Lat", "Lng"]]

In [13]:
# Add marker layer ontop of heat map
h_markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(h_markers)
fig


# Display figure

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi…